routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => ['role:admin']], function () {
    Route::get('/home', 'HomeController@index')->name('home');

    /*
     *Categories
     */
    Route::resource('categories', 'CategoryController', ['except' => ['show',]]);
    //ajax get brands of a category
    Route::post('get-category-brands', 'CategoryController@getCategoryBrands')->name('getCategoryBrands');
    
    Route::resource('brands', 'BrandController', ['except' => ['show',]]);
    //ajax get models of a brand
    Route::post('get-brand-models', 'BrandController@getBrandModels')->name('getBrandModels');
    
    Route::resource('models', 'ModelController', ['except' => ['show',]]);
    Route::resource('products', 'ProductController', ['except' => ['show',]]);
    Route::resource('users', 'UserController', ['except' => ['show',]]);
});

resources/views/regions/footer.blade.php
<!-- Main Footer -->
<footer class="main-footer">
    <!-- To the right -->
    <div class="pull-right hidden-xs">
      Made with <i class="far fa fa-heart"></i>
    </div>
    <!-- Default to the left -->
    <strong>Copyright &copy; 2017 <a href="#">HMA</a>.</strong> All rights reserved.
  </footer>

resources/views/regions/header.blade.php
<!-- Main Header -->
<header class="main-header">

  <!-- Logo -->
  <a href="index2.html" class="logo">
    <!-- mini logo for sidebar mini 50x50 pixels -->
    <span class="logo-mini"><b>W</b>dl</span>
    <!-- logo for regular state and mobile devices -->
    <span class="logo-lg"><b>WODDL</b>Backend</span>
  </a>

  <!-- Header Navbar -->
  <nav class="navbar navbar-static-top" role="navigation">
    <!-- Sidebar toggle button-->
    <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
        <span class="sr-only">Toggle navigation</span>
      </a>
    <!-- Navbar Right Menu -->
    <div class="navbar-custom-menu">
      <ul class="nav navbar-nav">
        <!-- User Account Menu -->
        <li class="dropdown user user-menu">
          <!-- Menu Toggle Button -->
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <!-- The user image in the navbar-->
            <img src="{{asset('bower_components/admin-lte/dist/img/user2-160x160.jpg')}}" class="user-image" alt="User Image">
            <!-- hidden-xs hides the username on small devices so only the image appears. -->
            <span class="hidden-xs">Alexander Pierce</span>
          </a>
          <ul class="dropdown-menu">
            <!-- The user image in the menu -->
            <li class="user-header">
              <img src="{{asset('bower_components/admin-lte/dist/img/user2-160x160.jpg')}}" class="img-circle" alt="User Image">

              <p>
                Alexander Pierce - Web Developer
                <small>Member since Nov. 2012</small>
              </p>
            </li>
            <!-- Menu Body -->
            <!-- <li class="user-body">
                <div class="row">
                  <div class="col-xs-4 text-center">
                    <a href="#">Followers</a>
                  </div>
                  <div class="col-xs-4 text-center">
                    <a href="#">Sales</a>
                  </div>
                  <div class="col-xs-4 text-center">
                    <a href="#">Friends</a>
                  </div>
                </div> -->
            <!-- /.row -->
        </li>
        <!-- Menu Footer-->
        <li class="user-footer">
          <div class="pull-left">
            <a href="#" class="btn btn-default btn-flat">Profile</a>
          </div>
          <div class="pull-right">
            {{-- <a href="#" class="btn btn-default btn-flat">Sign out</a> --}}
            <a href="{{ route('logout') }}" class="btn btn-default btn-flat" onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                                     Sign out
                                        </a>

            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
              {{ csrf_field() }}
            </form>
          </div>
        </li>
        </ul>
        </li>
      </ul>
    </div>
  </nav>
</header>

resources/views/regions/sidebar.blade.php
<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">

<!-- sidebar: style can be found in sidebar.less -->
<section class="sidebar">

  <!-- Sidebar user panel (optional) -->
  <div class="user-panel">
    <div class="pull-left image">
      <img src="{{asset('bower_components/admin-lte/dist/img/user2-160x160.jpg')}}" class="img-circle" alt="User Image">
    </div>
    <div class="pull-left info">
      <p>Alexander Pierce</p>
      <!-- Status -->
      <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
    </div>
  </div>

  <!-- Sidebar Menu -->
  <ul class="sidebar-menu" data-widget="tree">
    <li class="header">Menu</li>
    <!-- Optionally, you can add icons to the links -->
    <li class="active"><a href="#"><i class="fa fa-dashboard"></i> <span>Dashboard</span></a></li>
    <li class="treeview">
      <a href="#"><i class="fa fa-copyright"></i> <span>Category</span>
        <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
          </span>
      </a>
      <ul class="treeview-menu">
        <li><a href="{{ route('categories.index') }}">View</a></li>
        <li><a href="{{ route('categories.create') }}">Add</a></li>
      </ul>
    </li>
    <li class="treeview">
      <a href="#"><i class="fa fa-bitcoin"></i> <span>Brand</span>
        <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
          </span>
      </a>
      <ul class="treeview-menu">
        <li><a href="{{ route('brands.index') }}">View</a></li>
        <li><a href="{{ route('brands.create') }}">Add</a></li>
      </ul>
    </li>
    <li class="treeview">
      <a href="#"><i class="fa fa-maxcdn"></i> <span>Model</span>
        <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
          </span>
      </a>
      <ul class="treeview-menu">
        <li><a href="{{ route('models.index') }}">View</a></li>
        <li><a href="{{ route('models.create') }}">Add</a></li>
      </ul>
    </li>
    <li class="treeview">
      <a href="#"><i class="fa fa-camera"></i> <span>Product</span>
        <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
          </span>
      </a>
      <ul class="treeview-menu">
        <li><a href="{{ route('products.index') }}">View</a></li>
        <li><a href="{{ route('products.create') }}">Add</a></li>
        <li><a href="#">Non Reviewed Products</a></li>
      </ul>
    </li>
    <li class="treeview">
      <a href="#"><i class="fa fa-address-card"></i> <span>User</span>
        <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
          </span>
      </a>
      <ul class="treeview-menu">
        <li><a href="{{ route('users.index') }}">View</a></li>
        <li><a href="{{ route('users.create') }}">Add</a></li>
      </ul>
    </li>
    <li><a href="#"><i class="fa fa-trash"></i> <span>Deleted Accounts</span></a></li>
  </ul>
  <!-- /.sidebar-menu -->
</section>
<!-- /.sidebar -->
</aside>